# Generated by Django 5.2.17 on 2026-09-24 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField(blank=True, help_text='Procedures, therapy or treatment plan')),
                ('notes', models.TextField(blank=True, help_text='Treatment / progress notes')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 500 mg', max_length=80)),
                ('frequency', models.CharField(help_text='e.g. twice daily', max_length=80)),
                ('duration', models.CharField(blank=True, help_text='e.g. 7 days', max_length=80)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.medicalrecord')),
            ],
        ),
    ]
